# Generated by Django 6.0.1 on 2026-01-25 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='any_harmful_disease',
            field=models.TextField(blank=True, help_text='Any other harmful or chronic diseases'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='has_blood_pressure',
            field=models.BooleanField(default=False, verbose_name='Has Blood Pressure'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='has_cancer',
            field=models.BooleanField(default=False, verbose_name='Has Cancer History'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='has_diabetes',
            field=models.BooleanField(default=False, verbose_name='Has Diabetes (Sugar)'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='medical_history',
            field=models.TextField(blank=True, help_text='General medical history'),
        ),
    ]
